### ISSUE TITLE
DEVT add logo and display in searach function

### ISSUE THREAD

**Issue by Allen-DeHorizon** [MetaMask/contract-metadata#1055]
Dear MetaMask Support Team,

I'm Allen the BD manager of DeHorizon group. Last December, I suppose to some help request about our token information in Metamask, but it's not fixed yet. Now, I re-send the request again.

Our project token DEVT ( EthereumSmart Contract: 0xB5c578947de0fd71303F71F2C3d41767438bD0de) have two information need to update at below:

1. The token logo update, please check the attachment.
2. User cannot find our token DEVT via the search function, the only way now is to search smart contract which is not a good experience for our members.

We hope these issues could fix as soon as possible, and looking forward to your guy's feedback.

Thanks
Allen
![profile logo (1)](https://user-images.githubusercontent.com/106377173/170669127-103a6e2b-ee33-4977-9600-54e3e99a17e7.png)

**Comment by MRabenda** [comment]
@Allen-DeHorizon can you open PR with changes?

**Comment by MRabenda** [comment]
Please open PR or provide SVG image so I can do it for you
