### ISSUE TITLE
Adding MOA and OFE token into MM search list

### ISSUE THREAD

**Issue by Planet-Us** [MetaMask/contract-metadata#1142]
I've opened PR and merged MOA and OFE, but still cannot search both token on Metamask.
MOA : 
0xdf0162A6B3e9fDf0302c1e949739DeeaFafd8F89
OFE : 
0x9B6B9d2468E165a02FEf69E61B6D3D6CBC0Ac409

Do we have to wait for listing or we have to do something more?

Thank you in advance.

**Comment by ryanml** [comment]
Hi @Planet-Us - a PR has been created against the extension to update to the version of `contract-metadata` that will include these changes (v.2.2.0) - https://github.com/MetaMask/metamask-extension/pull/17230

This will be visible in the production extension when what is on develop after it's merged gets released, thanks!
