### ISSUE TITLE
requesting token icon additions

### ISSUE THREAD

**Issue by mapologize** [MetaMask/contract-metadata#1204]
Token Name : SMP Finance
Token Symbol : SMPF
Token Contract Address : 0x515e62a3ac560fd5df08536d08336e63aed3b182

URL or IPFS Hash of the Token Icon Image : 
https://ipfs.io/ipfs/QmYiyz867n4MLEASuj35NJDcaksZX3x6YGsb11xD9JvKzP

URL or IPFS Hash of the Token Manifest JSON File :
https://ipfs.io/ipfs/QmS4BqQnaCmuHajPgc4GfUhZ7V9Yib7GHduJ9fJzZP79Em

**Comment by MRabenda** [comment]
On which chain it is deployed?
