### ISSUE TITLE
IMX, GODS and GOG Token: Add to 'Import Token' Search List

### ISSUE THREAD

**Issue by ImmutableAden** [MetaMask/contract-metadata#1245]
IMX, GODS and GOG tokens do not appear when searched for in the 'Import Token' section of the MetaMask UI. 

![image](https://github.com/MetaMask/contract-metadata/assets/134032208/f640c479-cd96-4815-a2f2-2fef81b5321a)

Token Information:
IMX: https://etherscan.io/token/0xf57e7e7c23978c3caec3c3548e3d615c346e79ff 
GODS: https://etherscan.io/token/0xccc8cb5229b0ac8069c51fd58367fd1e622afd97
GOG: https://etherscan.io/token/0x9ab7bb7fdc60f4357ecfef43986818a2a3569c62

May they please be added to the Import Token search list.

**Comment by ImmutableAden** [comment]
Hey @MRabenda,

I can see GODS and GOG, but still cannot see IMX in my list. 

![image](https://github.com/MetaMask/contract-metadata/assets/134032208/8f5b4269-bedf-41b0-9021-881caa1b5bad)

May you please confirm?

**Comment by MRabenda** [comment]
It should be solved now, if there is still issue please let me know
