### ISSUE TITLE
Checking submitted logo

### ISSUE THREAD

**Issue by picardcapt1212** [MetaMask/contract-metadata#1290]
Hello team! I have a question about our team logo.

Though [#1288](https://github.com/MetaMask/contract-metadata/pull/1288) has been merged, the token logo in the metamask seems to be different as we expected.

The file I submitted has a white background, but the logo in the metamask still is the logo I submitted before.
Which displays different logo background color depending on system theme (dark/light).

Will it take a while for our submitted logo to show up in Metamask?

**Comment by MRabenda** [comment]
@picardcapt1212 it should be solved now
