### ISSUE TITLE
Token not showing up even when included in the latest release

### ISSUE THREAD

**Issue by souvikmishra** [MetaMask/contract-metadata#1304]
I had added the POND token to the repo in this PR. https://github.com/MetaMask/contract-metadata/pull/1276

Even though there is a marked [release containing this change](https://github.com/MetaMask/contract-metadata/releases/tag/v2.5.0), searching for POND on Ethereum mainnet in the metamask extension as well as the mobile app doesn't give any results (ref. screen shot for extension)
<img width="318" alt="Screenshot 2024-05-21 at 12 25 26 PM" src="https://github.com/MetaMask/contract-metadata/assets/58814221/f647ecf9-67fc-4c39-89f7-cecd04a5fe4a">

Is this something that usually takes some time? Any insight on this would be highly appreciated, also if there is something needed from my side please feel free to let me know 😃

**Comment by sahar-fehri** [comment]
Hello @souvikmishra , which version of extension and mobile are using? 🙏
