### ISSUE TITLE
Adding PACE token into MM search list

### ISSUE THREAD

**Issue by LeeWangKwang** [MetaMask/contract-metadata#1333]
I've opened PR and merged PACE, but still cannot search token on Metamask.
[PR Link](https://github.com/MetaMask/contract-metadata/pull/1202)

PACE
- 0x8Bc2bCb1b1896291942C36F3Cca3C1afA0Aaa7fd

Do i have to wait for listing or there is something to do more?

Thank you in advance.

**Comment by MRabenda** [comment]
Hey @LeeWangKwang - do you have this problem in Extension? If so which version are you running?

**Comment by LeeWangKwang** [comment]
> Hey @LeeWangKwang - do you have this problem in Extension? If so which version are you running?

yes, I am using chrome extension version 11.16.14

**Comment by MRabenda** [comment]
Would you mind to go to Setting -> Security & privacy -> and check if Token autodetection -> Autodetect tokens is enabled? And if not enable it?

**Comment by LeeWangKwang** [comment]
> Would you mind to go to Setting -> Security & privacy -> and check if Token autodetection -> Autodetect tokens is enabled? And if not enable it?

Thank you, I can see after enable "Autodetect tokens"

Is there something i should do for searching PACE Token without Token autodetection?

**Comment by MRabenda** [comment]
We have to release a new version of this repository (which will happen in the upcoming weeks) and include that release in the latest versions of MetaMask. Having installed a version with a specific list you would be able to see PACE without the autodetection feature.
