### ISSUE TITLE
When will the camp image be updated? The token icon is not visible yet.

### ISSUE THREAD

**Issue by JoshepJang** [MetaMask/contract-metadata#676]
When will the camp image be updated? The token icon is not visible yet.

@JoshepJang thank you so much - it looks perfect, awesome job!

_Originally posted by @xrn in https://github.com/MetaMask/contract-metadata/issues/673#issuecomment-743134640_

**Comment by xrn** [comment]
Hi,

First, we have to release a new version of this repo and then MetaMask has to include it in the extension release. It can take a few days

**Comment by JoshepJang** [comment]
> 안녕,
> 
> 먼저이 repo의 새 버전을 릴리스해야하며 MetaMask는이를 확장 릴리스에 포함해야합니다. 며칠이 걸릴 수 있습니다.



> Hi,
> 
> First, we have to release a new version of this repo and then MetaMask has to include it in the extension release. It can take a few days

thank very much.

**Comment by JoshepJang** [comment]
> Hi,
> 
> First, we have to release a new version of this repo and then MetaMask has to include it in the extension release. It can take a few days

thank very much.
