### ISSUE TITLE
When will the CAMP Token image be updated? Can I know the schedule?

### ISSUE THREAD

**Issue by JoshepJang** [MetaMask/contract-metadata#687]
When will the CAMP Token image be updated? The token icon is not yet displayed yet.  11 days have passed since I registered. Can I know the schedule?

Thanks.

=======================
Hi,

First, we have to release a new version of this repo and then MetaMask has to include it in the extension release. It can take a few days

_Originally posted by @xrn in https://github.com/MetaMask/contract-metadata/issues/676#issuecomment-744224939_

**Comment by Steake** [comment]
I also was unable to find any mention of a formal release cycle online?

**Comment by xrn** [comment]
CAMP logo is available in the newest Metamask extension version - ETL will be in the next release.
