### ISSUE TITLE
MMRL LOGO TO MethaMask

### ISSUE THREAD

**Issue by EITMJ** [MetaMask/contract-metadata#892]
Hi,

We are looking the ways to add logo to our Token at MethaMask.
SMART CONTRACT:
0x471bc0199e1b866b16827b9c4512daf1f6d53ca1

Kindly advise what we need to do?

![MMRL](https://user-images.githubusercontent.com/86794151/124201854-24d3e100-daea-11eb-90ea-b289db4a243a.jpg)

**Comment by EITMJ** [comment]
you can contact me:

Marius.j@eipinvestment.com

**Comment by EITMJ** [comment]
Any updates?

**Comment by xrn** [comment]
@EITMJ - can you please create pull request with svg image?

**Comment by EITMJ** [comment]
Not possible:
We only support PNG, GIF, or JPG pictures.
