### ISSUE TITLE
There is still no MAI token in MetaMask Chrome plugin

### ISSUE THREAD

**Issue by yell0w4x** [MetaMask/contract-metadata#894]
The required info for MAI has been merged by this pull request https://github.com/MetaMask/contract-metadata/pull/839. 

But unfortunately in the MetaMask Google Chome plugin MAI symbol and it's logo had not appeared. It's still necessary to add the token manually by adding MAI's smart contract as custom token.

Please we would really appreciate if you take a look at this issue.

**Comment by xrn** [comment]
Hi @yell0w4x if should be available soon with release 9.8.1

**Comment by andresilva** [comment]
Could you do a new release of `contract-metadata` so that more tokens are picked up on the upcoming metamask 9.8.1 release?

**Comment by xrn** [comment]
Released
