### ISSUE TITLE
Cryotomind(CR) token is not listed yet

### ISSUE THREAD

**Issue by cryptomindex** [MetaMask/contract-metadata#908]
The required info for CR has been merged by this pull request #889 .

We wait until the 9.8.1 version, But unfortunately in the MetaMask Google Chome plugin CR symbol and it's logo had not appeared. 

Could you please check this issue?

Thanks

**Comment by cryptomindex** [comment]
any update?!!

**Comment by cryptomindex** [comment]
@xrn  Could u please check this issue?

**Comment by xrn** [comment]
Released
